# filebeat.inputs:
# - type: container
#   paths: 
#     - '/var/lib/docker/containers/*/*.log'

# processors:
# - add_docker_metadata:
#     host: "unix:///var/run/docker.sock"

# - decode_json_fields:
#     fields: ["message"]
#     target: "json"
#     overwrite_keys: true

# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   indices:
#     - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

# logging.json: true
# logging.metrics.enabled: false

filebeat.prospectors:
- paths:
    - /apache-logs/access.log
  tags:
    - testenv
    - apache_access
  input_type: log
  document_type: apache_access
  fields_under_root: true

- paths:
    - /apache-logs/error.log
  tags:
    - testenv
    - apache_error
  input_type: log
  document_type: apache_error
  fields_under_root: true

output.kafka:
 # hosts: ["kafka1:9092", "kafka2:9092", "kafka3:9092"]
  hosts: ["kafka:9092"]
  topic: 'log'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
